server.port: 12345

api:
  auth-secret: ${AUTH_SECRET}

purge:
  cron:
    expression: 0 0 5 * * ?

---
spring:
  profiles: development
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localpostgres:5432/oauth2jwtauthentication
    username: dev
    password: q1w2e3r4
    initialization-mode: always
    dbcp2:
      validation-query: SELECT 1
  jpa:
    generate-ddl: true
    show-sql: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: jdbc:postgresql://localpostgres:5432/oauth2jwtauthentication
    user: dev
    locations: classpath:/db/migration
    password: q1w2e3r4
---
spring:
  profiles: test
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
AUTH_SECRET: yo
---

spring:
  profiles: integration