version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
#      - image: circleci/postgres:9.6
#        ports:
#          - "54321:5432"
#        environment:
#          - POSTGRES_USER=test
#          - POSTGRES_PASSWORD=
#          - POSTGRES_DB=

    working_directory: ~/mireles-auth

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: gradle dependencies
      - run: sudo apt install -y postgresql-client || true
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle clean test
      - run: gradle clean integrationTest